# Generated by Django 4.0.3 on 2024-01-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=50)),
                ('host_ip_address', models.CharField(max_length=50)),
                ('share', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('log_level', models.CharField(max_length=50)),
                ('sign', models.BooleanField(default=False)),
                ('encrypt', models.BooleanField(default=False)),
                ('trace', models.BooleanField(default=False)),
                ('min_dialect', models.IntegerField()),
                ('max_dialect', models.IntegerField()),
            ],
        ),
    ]
