# Generated by Django 4.0.3 on 2024-02-05 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_operatingsystem_alter_testsuite_encrypt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuitename',
            name='name',
        ),
        migrations.AddField(
            model_name='testsuitename',
            name='password',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid password format', regex='^[\\w.@+-]+$')]),
        ),
        migrations.AddField(
            model_name='testsuitename',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='testsuitename',
            name='operating_system',
            field=models.CharField(choices=[('centos', 'CentOS'), ('windows', 'Windows'), ('ubuntu', 'Ubuntu')], max_length=50),
        ),
        migrations.DeleteModel(
            name='OperatingSystem',
        ),
    ]
