# Generated by Django 4.0.3 on 2024-02-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_testsuite_max_dialect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='test_suite_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='dashboard.testsuitename', verbose_name='Test Suite Name'),
        ),
    ]
