# Generated by Django 4.0.3 on 2024-02-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_testsuitename_test_suite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuitename',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suite_names', to='dashboard.testsuite'),
        ),
    ]
