# Generated by Django 4.0.3 on 2024-02-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_testsuite_mapping_id_testsuitename_mapping_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='mapping_id',
        ),
        migrations.RemoveField(
            model_name='testsuitename',
            name='mapping_id',
        ),
        migrations.AddField(
            model_name='testsuitename',
            name='suite_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Test Suite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsuitename',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suite_names', to='dashboard.testsuite'),
        ),
    ]
