# Generated by Django 4.0.3 on 2024-01-31 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='host_ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='log_level',
            field=models.CharField(choices=[('Debug', 'Debug'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Info', 'Info')], max_length=50),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='max_dialect',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='min_dialect',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid password format', regex='^[\\w.@+-]+$')]),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='share',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Share must contain only alphanumeric characters', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
