# Generated by Django 4.0.3 on 2024-02-07 09:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_testsuitename_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='encrypt',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=False, verbose_name='Encrypt'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='host_ip_address',
            field=models.GenericIPAddressField(verbose_name='Host IP Address'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='log_level',
            field=models.CharField(choices=[('Debug', 'Debug'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Info', 'Info')], max_length=50, verbose_name='Log Level'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='max_dialect',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Max Dialect'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='min_dialect',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min Dialect'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid password format', regex='^[\\w.@+-]+$')], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='protocol',
            field=models.CharField(choices=[('SMB', 'SMB'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=50, verbose_name='Protocol'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='share',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Share must contain only alphanumeric characters', regex='^[a-zA-Z0-9]*$')], verbose_name='Share Name'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='sign',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=True, verbose_name='Sign'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='trace',
            field=models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], default=False, verbose_name='Trace'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='testsuitename',
            name='location',
            field=models.FileField(help_text='Enter folder location', upload_to='test_locations/', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='testsuitename',
            name='operating_system',
            field=models.CharField(choices=[('centos', 'CentOS'), ('windows', 'Windows'), ('ubuntu', 'Ubuntu')], max_length=50, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='testsuitename',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid password format', regex='^[\\w.@+-]+$')], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='testsuitename',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.testsuite', verbose_name='Test Suite'),
        ),
        migrations.AlterField(
            model_name='testsuitename',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='User Name'),
        ),
    ]
