# Generated by Django 4.0.3 on 2024-02-15 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_testsuite_test_suite_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='test_suite_name',
        ),
        migrations.AlterField(
            model_name='testsuitename',
            name='test_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='dashboard.testsuite', verbose_name='Test Suite'),
        ),
    ]
