# Generated by Django 4.0.3 on 2024-02-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_testsuitename_test_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='mapping_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mapping ID'),
        ),
        migrations.AddField(
            model_name='testsuitename',
            name='mapping_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mapping ID'),
        ),
    ]
