# Generated by Django 4.0.3 on 2024-02-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_testsuitename_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuitename',
            name='ip_address',
        ),
    ]
