# Generated by Django 4.0.3 on 2024-02-28 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_testsuitename_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuitename',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='max_dialect',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Dialect should be in the format 'DIALECT_SMB3_1_1'", regex='^[A-Za-z]+_[A-Za-z0-9_]+$')], verbose_name='Max Dialect'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='min_dialect',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Dialect should be in the format 'DIALECT_SMB3_1_1'", regex='^[A-Za-z]+_[A-Za-z0-9_]+$')], verbose_name='Min Dialect'),
        ),
    ]
