# Generated by Django 4.0.3 on 2024-02-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_testsuitename_ip_address_alter_testsuite_max_dialect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuitename',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
    ]
