# Generated by Django 4.0.3 on 2024-02-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_testsuitename_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuiteChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testsuitename',
            name='suite_name',
            field=models.CharField(choices=[('test_file_supersede_and_file_create.py', 'test_file_supersede_and_file_create.py'), ('test_file_open_and_file_open_if.py', 'test_file_open_and_file_open_if.py'), ('test_file_overwrite_and_file_overwrite_if.py', 'test_file_overwrite_and_file_overwrite_if.py')], max_length=50, verbose_name='Test Suite'),
        ),
    ]
