# Generated by Django 4.0.3 on 2024-02-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_testsuitechoice_alter_testsuitename_suite_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSuiteChoice',
        ),
    ]
